{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 31,
   "id": "6777a283-b486-4d18-964d-157fc41c239f",
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import sqlite3\n",
    "import pandas as pd\n",
    "import traceback\n",
    "import matplotlib.pyplot as plt\n",
    "import math \n",
    "\n",
    "def converter_valor(valor):\n",
    "    \n",
    "    \n",
    "    if type(valor) == str:\n",
    "\n",
    "        valor = valor.replace('R$', '').strip()\n",
    "        valor = valor.replace('.', '').replace(',', '.')\n",
    "        \n",
    "        if \"-\" in valor:\n",
    "            valor = valor.replace(\"-\",\"\").strip()\n",
    "        \n",
    "        # Identifica se é milhão (M) ou bilhão (B)\n",
    "        if 'B' in valor:\n",
    "            numero = float(valor.replace('B', '').replace(',', '.').strip())\n",
    "            return numero * 1_000_000_000, 'B'\n",
    "        elif 'M' in valor:\n",
    "            numero = float(valor.replace('M', '').replace(',', '.').strip())\n",
    "            return numero * 1_000_000, 'M'\n",
    "        elif 'T' in valor:\n",
    "            numero = float(valor.replace('T', '').replace(',', '.').strip())\n",
    "            return numero * 1_000_000_000_000, 'T'\n",
    "        elif \"mil\" in valor:\n",
    "            numero = float(valor.replace('mil', '').replace(',', '.').strip())\n",
    "            return numero * 1_000, 'mil'\n",
    "        else:\n",
    "            return valor, ''\n",
    "    else:\n",
    "        return 0"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c40eaa4e-9075-41a2-b092-96381d125a5f",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2a9aa4f8-270d-4460-863c-e37ab72c0e4b",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 32,
   "id": "fa891c9c-4f8f-439b-bf3c-5033b859fc6b",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Temp\\ipykernel_5068\\1880239182.py\", line 31, in <module>\n",
      "    tabela_df = pd.read_csv(diretorio+\"\\\\\"+str(tickerDir)+\"\\\\\"+str(files))\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\io\\parsers\\readers.py\", line 1026, in read_csv\n",
      "    return _read(filepath_or_buffer, kwds)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\io\\parsers\\readers.py\", line 626, in _read\n",
      "    return parser.read(nrows)\n",
      "           ^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\io\\parsers\\readers.py\", line 1923, in read\n",
      "    ) = self._engine.read(  # type: ignore[attr-defined]\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\io\\parsers\\c_parser_wrapper.py\", line 234, in read\n",
      "    chunks = self._reader.read_low_memory(nrows)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"parsers.pyx\", line 838, in pandas._libs.parsers.TextReader.read_low_memory\n",
      "  File \"parsers.pyx\", line 905, in pandas._libs.parsers.TextReader._read_rows\n",
      "  File \"parsers.pyx\", line 874, in pandas._libs.parsers.TextReader._tokenize_rows\n",
      "  File \"parsers.pyx\", line 891, in pandas._libs.parsers.TextReader._check_tokenize_status\n",
      "  File \"parsers.pyx\", line 2061, in pandas._libs.parsers.raise_parser_error\n",
      "pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 4, saw 2\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Temp\\ipykernel_5068\\1880239182.py\", line 113, in <module>\n",
      "    tabela_df[['receita_liquida_valor', 'receita_liquida_unidade']] = tabela_df['receita_liquida'].apply(converter_valor).apply(pd.Series)\n",
      "    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4299, in __setitem__\n",
      "    self._setitem_array(key, value)\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4358, in _setitem_array\n",
      "    self._iset_not_inplace(key, value)\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4377, in _iset_not_inplace\n",
      "    raise ValueError(\"Columns must be same length as key\")\n",
      "ValueError: Columns must be same length as key\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Temp\\ipykernel_5068\\1880239182.py\", line 113, in <module>\n",
      "    tabela_df[['receita_liquida_valor', 'receita_liquida_unidade']] = tabela_df['receita_liquida'].apply(converter_valor).apply(pd.Series)\n",
      "    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4299, in __setitem__\n",
      "    self._setitem_array(key, value)\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4358, in _setitem_array\n",
      "    self._iset_not_inplace(key, value)\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4377, in _iset_not_inplace\n",
      "    raise ValueError(\"Columns must be same length as key\")\n",
      "ValueError: Columns must be same length as key\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Temp\\ipykernel_5068\\1880239182.py\", line 113, in <module>\n",
      "    tabela_df[['receita_liquida_valor', 'receita_liquida_unidade']] = tabela_df['receita_liquida'].apply(converter_valor).apply(pd.Series)\n",
      "    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4299, in __setitem__\n",
      "    self._setitem_array(key, value)\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4358, in _setitem_array\n",
      "    self._iset_not_inplace(key, value)\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4377, in _iset_not_inplace\n",
      "    raise ValueError(\"Columns must be same length as key\")\n",
      "ValueError: Columns must be same length as key\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Temp\\ipykernel_5068\\1880239182.py\", line 113, in <module>\n",
      "    tabela_df[['receita_liquida_valor', 'receita_liquida_unidade']] = tabela_df['receita_liquida'].apply(converter_valor).apply(pd.Series)\n",
      "    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4299, in __setitem__\n",
      "    self._setitem_array(key, value)\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4358, in _setitem_array\n",
      "    self._iset_not_inplace(key, value)\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4377, in _iset_not_inplace\n",
      "    raise ValueError(\"Columns must be same length as key\")\n",
      "ValueError: Columns must be same length as key\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Temp\\ipykernel_5068\\1880239182.py\", line 113, in <module>\n",
      "    tabela_df[['receita_liquida_valor', 'receita_liquida_unidade']] = tabela_df['receita_liquida'].apply(converter_valor).apply(pd.Series)\n",
      "    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4299, in __setitem__\n",
      "    self._setitem_array(key, value)\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4358, in _setitem_array\n",
      "    self._iset_not_inplace(key, value)\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4377, in _iset_not_inplace\n",
      "    raise ValueError(\"Columns must be same length as key\")\n",
      "ValueError: Columns must be same length as key\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Temp\\ipykernel_5068\\1880239182.py\", line 113, in <module>\n",
      "    tabela_df[['receita_liquida_valor', 'receita_liquida_unidade']] = tabela_df['receita_liquida'].apply(converter_valor).apply(pd.Series)\n",
      "    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4299, in __setitem__\n",
      "    self._setitem_array(key, value)\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4358, in _setitem_array\n",
      "    self._iset_not_inplace(key, value)\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4377, in _iset_not_inplace\n",
      "    raise ValueError(\"Columns must be same length as key\")\n",
      "ValueError: Columns must be same length as key\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Temp\\ipykernel_5068\\1880239182.py\", line 113, in <module>\n",
      "    tabela_df[['receita_liquida_valor', 'receita_liquida_unidade']] = tabela_df['receita_liquida'].apply(converter_valor).apply(pd.Series)\n",
      "    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4299, in __setitem__\n",
      "    self._setitem_array(key, value)\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4358, in _setitem_array\n",
      "    self._iset_not_inplace(key, value)\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4377, in _iset_not_inplace\n",
      "    raise ValueError(\"Columns must be same length as key\")\n",
      "ValueError: Columns must be same length as key\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Temp\\ipykernel_5068\\1880239182.py\", line 113, in <module>\n",
      "    tabela_df[['receita_liquida_valor', 'receita_liquida_unidade']] = tabela_df['receita_liquida'].apply(converter_valor).apply(pd.Series)\n",
      "    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4299, in __setitem__\n",
      "    self._setitem_array(key, value)\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4358, in _setitem_array\n",
      "    self._iset_not_inplace(key, value)\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4377, in _iset_not_inplace\n",
      "    raise ValueError(\"Columns must be same length as key\")\n",
      "ValueError: Columns must be same length as key\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Temp\\ipykernel_5068\\1880239182.py\", line 113, in <module>\n",
      "    tabela_df[['receita_liquida_valor', 'receita_liquida_unidade']] = tabela_df['receita_liquida'].apply(converter_valor).apply(pd.Series)\n",
      "    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4299, in __setitem__\n",
      "    self._setitem_array(key, value)\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4358, in _setitem_array\n",
      "    self._iset_not_inplace(key, value)\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4377, in _iset_not_inplace\n",
      "    raise ValueError(\"Columns must be same length as key\")\n",
      "ValueError: Columns must be same length as key\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Temp\\ipykernel_5068\\1880239182.py\", line 113, in <module>\n",
      "    tabela_df[['receita_liquida_valor', 'receita_liquida_unidade']] = tabela_df['receita_liquida'].apply(converter_valor).apply(pd.Series)\n",
      "    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4299, in __setitem__\n",
      "    self._setitem_array(key, value)\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4358, in _setitem_array\n",
      "    self._iset_not_inplace(key, value)\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4377, in _iset_not_inplace\n",
      "    raise ValueError(\"Columns must be same length as key\")\n",
      "ValueError: Columns must be same length as key\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Temp\\ipykernel_5068\\1880239182.py\", line 113, in <module>\n",
      "    tabela_df[['receita_liquida_valor', 'receita_liquida_unidade']] = tabela_df['receita_liquida'].apply(converter_valor).apply(pd.Series)\n",
      "    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4299, in __setitem__\n",
      "    self._setitem_array(key, value)\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4358, in _setitem_array\n",
      "    self._iset_not_inplace(key, value)\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4377, in _iset_not_inplace\n",
      "    raise ValueError(\"Columns must be same length as key\")\n",
      "ValueError: Columns must be same length as key\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Temp\\ipykernel_5068\\1880239182.py\", line 113, in <module>\n",
      "    tabela_df[['receita_liquida_valor', 'receita_liquida_unidade']] = tabela_df['receita_liquida'].apply(converter_valor).apply(pd.Series)\n",
      "    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4299, in __setitem__\n",
      "    self._setitem_array(key, value)\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4358, in _setitem_array\n",
      "    self._iset_not_inplace(key, value)\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4377, in _iset_not_inplace\n",
      "    raise ValueError(\"Columns must be same length as key\")\n",
      "ValueError: Columns must be same length as key\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Temp\\ipykernel_5068\\1880239182.py\", line 113, in <module>\n",
      "    tabela_df[['receita_liquida_valor', 'receita_liquida_unidade']] = tabela_df['receita_liquida'].apply(converter_valor).apply(pd.Series)\n",
      "    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4299, in __setitem__\n",
      "    self._setitem_array(key, value)\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4358, in _setitem_array\n",
      "    self._iset_not_inplace(key, value)\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4377, in _iset_not_inplace\n",
      "    raise ValueError(\"Columns must be same length as key\")\n",
      "ValueError: Columns must be same length as key\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Temp\\ipykernel_5068\\1880239182.py\", line 113, in <module>\n",
      "    tabela_df[['receita_liquida_valor', 'receita_liquida_unidade']] = tabela_df['receita_liquida'].apply(converter_valor).apply(pd.Series)\n",
      "    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4299, in __setitem__\n",
      "    self._setitem_array(key, value)\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4358, in _setitem_array\n",
      "    self._iset_not_inplace(key, value)\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4377, in _iset_not_inplace\n",
      "    raise ValueError(\"Columns must be same length as key\")\n",
      "ValueError: Columns must be same length as key\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Temp\\ipykernel_5068\\1880239182.py\", line 113, in <module>\n",
      "    tabela_df[['receita_liquida_valor', 'receita_liquida_unidade']] = tabela_df['receita_liquida'].apply(converter_valor).apply(pd.Series)\n",
      "    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4299, in __setitem__\n",
      "    self._setitem_array(key, value)\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4358, in _setitem_array\n",
      "    self._iset_not_inplace(key, value)\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4377, in _iset_not_inplace\n",
      "    raise ValueError(\"Columns must be same length as key\")\n",
      "ValueError: Columns must be same length as key\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Temp\\ipykernel_5068\\1880239182.py\", line 113, in <module>\n",
      "    tabela_df[['receita_liquida_valor', 'receita_liquida_unidade']] = tabela_df['receita_liquida'].apply(converter_valor).apply(pd.Series)\n",
      "    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4299, in __setitem__\n",
      "    self._setitem_array(key, value)\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4358, in _setitem_array\n",
      "    self._iset_not_inplace(key, value)\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4377, in _iset_not_inplace\n",
      "    raise ValueError(\"Columns must be same length as key\")\n",
      "ValueError: Columns must be same length as key\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Temp\\ipykernel_5068\\1880239182.py\", line 113, in <module>\n",
      "    tabela_df[['receita_liquida_valor', 'receita_liquida_unidade']] = tabela_df['receita_liquida'].apply(converter_valor).apply(pd.Series)\n",
      "    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4299, in __setitem__\n",
      "    self._setitem_array(key, value)\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4358, in _setitem_array\n",
      "    self._iset_not_inplace(key, value)\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4377, in _iset_not_inplace\n",
      "    raise ValueError(\"Columns must be same length as key\")\n",
      "ValueError: Columns must be same length as key\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Temp\\ipykernel_5068\\1880239182.py\", line 113, in <module>\n",
      "    tabela_df[['receita_liquida_valor', 'receita_liquida_unidade']] = tabela_df['receita_liquida'].apply(converter_valor).apply(pd.Series)\n",
      "    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4299, in __setitem__\n",
      "    self._setitem_array(key, value)\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4358, in _setitem_array\n",
      "    self._iset_not_inplace(key, value)\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4377, in _iset_not_inplace\n",
      "    raise ValueError(\"Columns must be same length as key\")\n",
      "ValueError: Columns must be same length as key\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Temp\\ipykernel_5068\\1880239182.py\", line 113, in <module>\n",
      "    tabela_df[['receita_liquida_valor', 'receita_liquida_unidade']] = tabela_df['receita_liquida'].apply(converter_valor).apply(pd.Series)\n",
      "    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4299, in __setitem__\n",
      "    self._setitem_array(key, value)\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4358, in _setitem_array\n",
      "    self._iset_not_inplace(key, value)\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4377, in _iset_not_inplace\n",
      "    raise ValueError(\"Columns must be same length as key\")\n",
      "ValueError: Columns must be same length as key\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Temp\\ipykernel_5068\\1880239182.py\", line 113, in <module>\n",
      "    tabela_df[['receita_liquida_valor', 'receita_liquida_unidade']] = tabela_df['receita_liquida'].apply(converter_valor).apply(pd.Series)\n",
      "    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4299, in __setitem__\n",
      "    self._setitem_array(key, value)\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4358, in _setitem_array\n",
      "    self._iset_not_inplace(key, value)\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4377, in _iset_not_inplace\n",
      "    raise ValueError(\"Columns must be same length as key\")\n",
      "ValueError: Columns must be same length as key\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Temp\\ipykernel_5068\\1880239182.py\", line 86, in <module>\n",
      "    tabela_df[['market_cap_empresa_valor', 'market_cap_empresa_unidade']] = tabela_df['market_cap_empresa'].apply(converter_valor).apply(pd.Series)\n",
      "    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4299, in __setitem__\n",
      "    self._setitem_array(key, value)\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4341, in _setitem_array\n",
      "    check_key_length(self.columns, key, value)\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\indexers\\utils.py\", line 390, in check_key_length\n",
      "    raise ValueError(\"Columns must be same length as key\")\n",
      "ValueError: Columns must be same length as key\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Temp\\ipykernel_5068\\1880239182.py\", line 113, in <module>\n",
      "    tabela_df[['receita_liquida_valor', 'receita_liquida_unidade']] = tabela_df['receita_liquida'].apply(converter_valor).apply(pd.Series)\n",
      "    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4299, in __setitem__\n",
      "    self._setitem_array(key, value)\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4358, in _setitem_array\n",
      "    self._iset_not_inplace(key, value)\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4377, in _iset_not_inplace\n",
      "    raise ValueError(\"Columns must be same length as key\")\n",
      "ValueError: Columns must be same length as key\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Temp\\ipykernel_5068\\1880239182.py\", line 113, in <module>\n",
      "    tabela_df[['receita_liquida_valor', 'receita_liquida_unidade']] = tabela_df['receita_liquida'].apply(converter_valor).apply(pd.Series)\n",
      "    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4299, in __setitem__\n",
      "    self._setitem_array(key, value)\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4358, in _setitem_array\n",
      "    self._iset_not_inplace(key, value)\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4377, in _iset_not_inplace\n",
      "    raise ValueError(\"Columns must be same length as key\")\n",
      "ValueError: Columns must be same length as key\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Temp\\ipykernel_5068\\1880239182.py\", line 113, in <module>\n",
      "    tabela_df[['receita_liquida_valor', 'receita_liquida_unidade']] = tabela_df['receita_liquida'].apply(converter_valor).apply(pd.Series)\n",
      "    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4299, in __setitem__\n",
      "    self._setitem_array(key, value)\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4358, in _setitem_array\n",
      "    self._iset_not_inplace(key, value)\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4377, in _iset_not_inplace\n",
      "    raise ValueError(\"Columns must be same length as key\")\n",
      "ValueError: Columns must be same length as key\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Temp\\ipykernel_5068\\1880239182.py\", line 113, in <module>\n",
      "    tabela_df[['receita_liquida_valor', 'receita_liquida_unidade']] = tabela_df['receita_liquida'].apply(converter_valor).apply(pd.Series)\n",
      "    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4299, in __setitem__\n",
      "    self._setitem_array(key, value)\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4358, in _setitem_array\n",
      "    self._iset_not_inplace(key, value)\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4377, in _iset_not_inplace\n",
      "    raise ValueError(\"Columns must be same length as key\")\n",
      "ValueError: Columns must be same length as key\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Temp\\ipykernel_5068\\1880239182.py\", line 113, in <module>\n",
      "    tabela_df[['receita_liquida_valor', 'receita_liquida_unidade']] = tabela_df['receita_liquida'].apply(converter_valor).apply(pd.Series)\n",
      "    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4299, in __setitem__\n",
      "    self._setitem_array(key, value)\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4358, in _setitem_array\n",
      "    self._iset_not_inplace(key, value)\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4377, in _iset_not_inplace\n",
      "    raise ValueError(\"Columns must be same length as key\")\n",
      "ValueError: Columns must be same length as key\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Temp\\ipykernel_5068\\1880239182.py\", line 113, in <module>\n",
      "    tabela_df[['receita_liquida_valor', 'receita_liquida_unidade']] = tabela_df['receita_liquida'].apply(converter_valor).apply(pd.Series)\n",
      "    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4299, in __setitem__\n",
      "    self._setitem_array(key, value)\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4358, in _setitem_array\n",
      "    self._iset_not_inplace(key, value)\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4377, in _iset_not_inplace\n",
      "    raise ValueError(\"Columns must be same length as key\")\n",
      "ValueError: Columns must be same length as key\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Temp\\ipykernel_5068\\1880239182.py\", line 113, in <module>\n",
      "    tabela_df[['receita_liquida_valor', 'receita_liquida_unidade']] = tabela_df['receita_liquida'].apply(converter_valor).apply(pd.Series)\n",
      "    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4299, in __setitem__\n",
      "    self._setitem_array(key, value)\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4358, in _setitem_array\n",
      "    self._iset_not_inplace(key, value)\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4377, in _iset_not_inplace\n",
      "    raise ValueError(\"Columns must be same length as key\")\n",
      "ValueError: Columns must be same length as key\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Temp\\ipykernel_5068\\1880239182.py\", line 113, in <module>\n",
      "    tabela_df[['receita_liquida_valor', 'receita_liquida_unidade']] = tabela_df['receita_liquida'].apply(converter_valor).apply(pd.Series)\n",
      "    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4299, in __setitem__\n",
      "    self._setitem_array(key, value)\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4358, in _setitem_array\n",
      "    self._iset_not_inplace(key, value)\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4377, in _iset_not_inplace\n",
      "    raise ValueError(\"Columns must be same length as key\")\n",
      "ValueError: Columns must be same length as key\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Temp\\ipykernel_5068\\1880239182.py\", line 113, in <module>\n",
      "    tabela_df[['receita_liquida_valor', 'receita_liquida_unidade']] = tabela_df['receita_liquida'].apply(converter_valor).apply(pd.Series)\n",
      "    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4299, in __setitem__\n",
      "    self._setitem_array(key, value)\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4358, in _setitem_array\n",
      "    self._iset_not_inplace(key, value)\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4377, in _iset_not_inplace\n",
      "    raise ValueError(\"Columns must be same length as key\")\n",
      "ValueError: Columns must be same length as key\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Temp\\ipykernel_5068\\1880239182.py\", line 113, in <module>\n",
      "    tabela_df[['receita_liquida_valor', 'receita_liquida_unidade']] = tabela_df['receita_liquida'].apply(converter_valor).apply(pd.Series)\n",
      "    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4299, in __setitem__\n",
      "    self._setitem_array(key, value)\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4358, in _setitem_array\n",
      "    self._iset_not_inplace(key, value)\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4377, in _iset_not_inplace\n",
      "    raise ValueError(\"Columns must be same length as key\")\n",
      "ValueError: Columns must be same length as key\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Temp\\ipykernel_5068\\1880239182.py\", line 113, in <module>\n",
      "    tabela_df[['receita_liquida_valor', 'receita_liquida_unidade']] = tabela_df['receita_liquida'].apply(converter_valor).apply(pd.Series)\n",
      "    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4299, in __setitem__\n",
      "    self._setitem_array(key, value)\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4358, in _setitem_array\n",
      "    self._iset_not_inplace(key, value)\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4377, in _iset_not_inplace\n",
      "    raise ValueError(\"Columns must be same length as key\")\n",
      "ValueError: Columns must be same length as key\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Temp\\ipykernel_5068\\1880239182.py\", line 113, in <module>\n",
      "    tabela_df[['receita_liquida_valor', 'receita_liquida_unidade']] = tabela_df['receita_liquida'].apply(converter_valor).apply(pd.Series)\n",
      "    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4299, in __setitem__\n",
      "    self._setitem_array(key, value)\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4358, in _setitem_array\n",
      "    self._iset_not_inplace(key, value)\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4377, in _iset_not_inplace\n",
      "    raise ValueError(\"Columns must be same length as key\")\n",
      "ValueError: Columns must be same length as key\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Temp\\ipykernel_5068\\1880239182.py\", line 113, in <module>\n",
      "    tabela_df[['receita_liquida_valor', 'receita_liquida_unidade']] = tabela_df['receita_liquida'].apply(converter_valor).apply(pd.Series)\n",
      "    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4299, in __setitem__\n",
      "    self._setitem_array(key, value)\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4358, in _setitem_array\n",
      "    self._iset_not_inplace(key, value)\n",
      "  File \"C:\\Users\\harri\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4377, in _iset_not_inplace\n",
      "    raise ValueError(\"Columns must be same length as key\")\n",
      "ValueError: Columns must be same length as key\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Salvando\n"
     ]
    }
   ],
   "source": [
    "diretorio = \"C:\\\\Users\\\\harri\\\\Documents\\\\Programacao\\\\Python\\\\ScrappingFinanceiros\\\\DadosDeMercado\\\\dividendos\"\n",
    "\n",
    "banco = \"db.sqlite3\"\n",
    "\n",
    "\n",
    "resumoEmpresaBp_df = pd.DataFrame()\n",
    "resumoEmpresaDre3Meses_df = pd.DataFrame()\n",
    "resumoEmpresaDre12Meses_df = pd.DataFrame()\n",
    "resumoEmpresaFc3Meses_df = pd.DataFrame()\n",
    "resumoEmpresaFc12Meses_df = pd.DataFrame()\n",
    "resumoEmpresaPrecosRelativos_df= pd.DataFrame()\n",
    "\n",
    "\n",
    "for tickerDir in os.listdir(diretorio):\n",
    "    \n",
    "    if os.path.isdir(tickerDir):\n",
    "        \n",
    "        try:\n",
    "            conn = sqlite3.connect(banco)\n",
    "            cursor = conn.cursor()\n",
    "            \n",
    "            cursor.execute(\"SELECT id_ticker FROM tickers WHERE Ticker = ?\", (tickerDir,))\n",
    "            resultado = cursor.fetchone()\n",
    "            \n",
    "            conn.commit()\n",
    "            conn.close()\n",
    "\n",
    "            \n",
    "            for files in os.listdir(diretorio+\"\\\\\"+tickerDir):\n",
    "                \n",
    "                tabela_df = pd.read_csv(diretorio+\"\\\\\"+str(tickerDir)+\"\\\\\"+str(files))\n",
    "                tabela_df[\"ticker\"] = resultado[0]\n",
    "                tabela_df = tabela_df.drop(tabela_df.columns[[0]], axis=1)\n",
    "\n",
    "                tabela_df = tabela_df.iloc[::-1].reset_index(drop=True)\n",
    "                \n",
    "                \n",
    "                if \"resumoEmpresaBp\" in files:\n",
    "                    \n",
    "                    tabela_df[['ativo_total_valor', 'ativo_total_unidade']] = tabela_df['ativo_total'].apply(converter_valor).apply(pd.Series)\n",
    "                    tabela_df[['patrimonio_liq_valor', 'patrimonio_liq_unidade']] = tabela_df['patrimonio_liq'].apply(converter_valor).apply(pd.Series)\n",
    "                    tabela_df[['vlr_patrimonial_acao_valor', 'vlr_patrimonial_unidade']] = tabela_df['vlr_patrimonial_acao'].apply(converter_valor).apply(pd.Series)\n",
    "                    tabela_df['ativo_total_valor'] = (tabela_df['ativo_total_valor'])\n",
    "                    tabela_df['patrimonio_liq_valor'] = (tabela_df['patrimonio_liq_valor'])\n",
    "                    \n",
    "                    resumoEmpresaBp_df = pd.concat([resumoEmpresaBp_df,tabela_df])\n",
    "                \n",
    "                \n",
    "                if \"resumoEmpresaFc3Meses\" in files:\n",
    "\n",
    "                        tabela_df[['fluxo_caixa_operacional_valor', 'fluxo_caixa_operacional_unidade']] = tabela_df['fluxo_caixa_operacional'].apply(converter_valor).apply(pd.Series)\n",
    "                        tabela_df[['fluxo_caixa_investimentos_valor', 'fluxo_caixa_investimentos_unidade']] = tabela_df['fluxo_caixa_investimentos'].apply(converter_valor).apply(pd.Series)\n",
    "                        tabela_df[['fluxo_caixa_financiamentos_valor', 'fluxo_caixa_financiamentos_unidade']] = tabela_df['fluxo_caixa_financiamentos'].apply(converter_valor).apply(pd.Series)\n",
    "                        tabela_df[['fluxo_caixa_equivalentes_valor', 'fluxo_caixa_equivalentes_unidade']] = tabela_df['fluxo_caixa_equivalentes'].apply(converter_valor).apply(pd.Series)\n",
    "                        \n",
    "\n",
    "                        tabela_df['fluxo_caixa_operacional_valor'] = (tabela_df['fluxo_caixa_operacional_valor'])\n",
    "                        tabela_df['fluxo_caixa_investimentos_valor'] = (tabela_df['fluxo_caixa_investimentos_valor'])\n",
    "                        tabela_df['fluxo_caixa_financiamentos_valor'] = (tabela_df['fluxo_caixa_financiamentos_valor'])\n",
    "                        tabela_df['fluxo_caixa_equivalentes_valor'] = (tabela_df['fluxo_caixa_equivalentes_valor'])\n",
    "                        \n",
    "                        resumoEmpresaFc3Meses_df = pd.concat([resumoEmpresaFc3Meses_df,tabela_df])\n",
    "                        \n",
    "                    \n",
    "                \n",
    "                if \"resumoEmpresaFc12Meses\" in files:\n",
    "\n",
    "                        \n",
    "                        tabela_df[['fluxo_caixa_operacional_valor', 'fluxo_caixa_operacional_unidade']] = tabela_df['fluxo_caixa_operacional'].apply(converter_valor).apply(pd.Series)\n",
    "                        tabela_df[['fluxo_caixa_investimentos_valor', 'fluxo_caixa_investimentos_unidade']] = tabela_df['fluxo_caixa_investimentos'].apply(converter_valor).apply(pd.Series)\n",
    "                        tabela_df[['fluxo_caixa_financiamentos_valor', 'fluxo_caixa_financiamentos_unidade']] = tabela_df['fluxo_caixa_financiamentos'].apply(converter_valor).apply(pd.Series)\n",
    "                        tabela_df[['fluxo_caixa_equivalentes_valor', 'fluxo_caixa_equivalentes_unidade']] = tabela_df['fluxo_caixa_equivalentes'].apply(converter_valor).apply(pd.Series)\n",
    "                        \n",
    "\n",
    "                        tabela_df['fluxo_caixa_operacional_valor'] = (tabela_df['fluxo_caixa_operacional_valor'])\n",
    "                        tabela_df['fluxo_caixa_investimentos_valor'] = (tabela_df['fluxo_caixa_investimentos_valor'])\n",
    "                        tabela_df['fluxo_caixa_financiamentos_valor'] = (tabela_df['fluxo_caixa_financiamentos_valor'])\n",
    "                        tabela_df['fluxo_caixa_equivalentes_valor'] = (tabela_df['fluxo_caixa_equivalentes_valor'])\n",
    "                        \n",
    "                        resumoEmpresaFc12Meses_df = pd.concat([resumoEmpresaFc12Meses_df,tabela_df])\n",
    "                        \n",
    "                \n",
    "                \n",
    "                if \"resumoEmpresaPrecosRelativos\" in files:\n",
    "\n",
    "                        tabela_df[['market_cap_empresa_valor', 'market_cap_empresa_unidade']] = tabela_df['market_cap_empresa'].apply(converter_valor).apply(pd.Series)\n",
    "                        \n",
    "                        resumoEmpresaPrecosRelativos_df = pd.concat([resumoEmpresaPrecosRelativos_df,tabela_df])\n",
    "                \n",
    "\n",
    "                if \"resumoEmpresaDre3Meses\" in files:\n",
    "\n",
    "                        tabela_df[['receita_liquida_valor', 'receita_liquida_unidade']] = tabela_df['receita_liquida'].apply(converter_valor).apply(pd.Series)\n",
    "                        tabela_df[['resultado_bruto_valor', 'resultado_bruto_unidade']] = tabela_df['resultado_bruto'].apply(converter_valor).apply(pd.Series)\n",
    "                        tabela_df[['ebit_valor', 'ebit_unidade']] = tabela_df['ebit'].apply(converter_valor).apply(pd.Series)\n",
    "                        tabela_df[['depreciacao_valor', 'depreciacao_unidade']] = tabela_df['depreciacao'].apply(converter_valor).apply(pd.Series)\n",
    "                        tabela_df[['ebitda_valor', 'ebitda_unidade']] = tabela_df['ebitda'].apply(converter_valor).apply(pd.Series)\n",
    "                        tabela_df[['lucro_liquido_valor', 'lucro_liquido_unidade']] = tabela_df['lucro_liquido'].apply(converter_valor).apply(pd.Series)\n",
    "                        tabela_df[['lucro_acao_valor', 'lucro_acao_unidade']] = tabela_df['lucro_acao'].apply(converter_valor).apply(pd.Series)\n",
    "\n",
    "                        tabela_df['receita_liquida_valor'] = (tabela_df['receita_liquida_valor'])\n",
    "                        tabela_df['resultado_bruto_valor'] = (tabela_df['resultado_bruto_valor'])\n",
    "                        tabela_df['ebit_valor'] = (tabela_df['ebit_valor'])\n",
    "                        tabela_df['depreciacao_valor'] = (tabela_df['depreciacao_valor'])\n",
    "                        tabela_df['lucro_liquido_valor'] = (tabela_df['lucro_liquido_valor'])\n",
    "                        tabela_df['lucro_acao_valor'] = (tabela_df['lucro_acao_valor'])\n",
    "\n",
    "                        resumoEmpresaDre3Meses_df = pd.concat([resumoEmpresaDre3Meses_df,tabela_df])\n",
    "                \n",
    "                \n",
    "                if \"resumoEmpresaDre12Meses\" in files:\n",
    "\n",
    "                        tabela_df[['receita_liquida_valor', 'receita_liquida_unidade']] = tabela_df['receita_liquida'].apply(converter_valor).apply(pd.Series)\n",
    "                        tabela_df[['resultado_bruto_valor', 'resultado_bruto_unidade']] = tabela_df['resultado_bruto'].apply(converter_valor).apply(pd.Series)\n",
    "                        tabela_df[['ebit_valor', 'ebit_unidade']] = tabela_df['ebit'].apply(converter_valor).apply(pd.Series)\n",
    "                        tabela_df[['depreciacao_valor', 'depreciacao_unidade']] = tabela_df['depreciacao'].apply(converter_valor).apply(pd.Series)\n",
    "                        tabela_df[['ebitda_valor', 'ebitda_unidade']] = tabela_df['ebitda'].apply(converter_valor).apply(pd.Series)\n",
    "                        tabela_df[['lucro_liquido_valor', 'lucro_liquido_unidade']] = tabela_df['lucro_liquido'].apply(converter_valor).apply(pd.Series)\n",
    "                        tabela_df[['lucro_acao_valor', 'lucro_acao_unidade']] = tabela_df['lucro_acao'].apply(converter_valor).apply(pd.Series)\n",
    "\n",
    "                        tabela_df['receita_liquida_valor'] = (tabela_df['receita_liquida_valor'])\n",
    "                        tabela_df['resultado_bruto_valor'] = (tabela_df['resultado_bruto_valor'])\n",
    "                        tabela_df['ebit_valor'] = (tabela_df['ebit_valor'])\n",
    "                        tabela_df['depreciacao_valor'] = (tabela_df['depreciacao_valor'])\n",
    "                        tabela_df['lucro_liquido_valor'] = (tabela_df['lucro_liquido_valor'])\n",
    "                        tabela_df['lucro_acao_valor'] = (tabela_df['lucro_acao_valor'])\n",
    "\n",
    "                        resumoEmpresaDre12Meses_df = pd.concat([resumoEmpresaDre12Meses_df,tabela_df])\n",
    "        \n",
    "        except Exception as e:\n",
    "            traceback.print_exc()\n",
    "\n",
    "\n",
    "\n",
    "path = \"resumos\"\n",
    "print(\"Salvando\")\n",
    "resumoEmpresaBp_df.to_csv(path+\"\\\\resumoEmpresaBp_df.csv\")\n",
    "resumoEmpresaDre3Meses_df.to_csv(path+\"\\\\resumoEmpresaDre3Meses_df.csv\")\n",
    "resumoEmpresaDre12Meses_df.to_csv(path+\"\\\\resumoEmpresaDre12Meses_df.csv\")\n",
    "resumoEmpresaFc3Meses_df.to_csv(path+\"\\\\resumoEmpresaFc3Meses_df.csv\")\n",
    "resumoEmpresaFc12Meses_df.to_csv(path+\"\\\\resumoEmpresaFc12Meses_df.csv\")\n",
    "resumoEmpresaPrecosRelativos_df.to_csv(path+\"\\\\resumoEmpresaPrecosRelativos_df.csv\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2a714ce6-3335-4671-998d-3286935c8290",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "349e6953-1093-48b7-9574-085dce01be21",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c68a0721-505b-4f74-bcd9-41e54dbeb02a",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4d950508-74ec-4c7b-afa6-aecdbc011492",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "502c8cb8-2fae-4919-a521-df64786622e1",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6099916e-8aba-44c1-9e6a-962851d1dbc5",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
